### ISSUE TITLE
Server crashes every few hours

### ISSUE THREAD

**Issue by tbankstemp** [Tyrsis/SE-Community-Mod-API#23]
I get this crash every 2 or 3 hours. I have your GPS mod and your Dedicated Essentials Client Side Mod for clients.
Server runs SESE and Extender both up to date.
>>>>>>
2015-01-01 17:33:53.691 - Player entered game, starting movement.
2015-01-01 17:33:53.693 - Attempting to move user to: (392, 309, 30)
2015-01-01 17:33:53.929: Logging off Steam...
2015-01-01 17:33:53.929: Shutting down server...
2015-01-01 17:33:54.085: Done
Server has stopped running
2015-01-01 17:33:54.100 - Unloading plugin 'f767bda5-0a8c-4813-85fd-a5a2341778e8'
2015-01-01 17:33:54.116 - Shutting down plugin: Dedicated Server Essentials - 1.0.2.1197
2015-01-01 17:33:54.116 - Handler Problems: 500 - System.Threading.ThreadAbortException: T
hread was being aborted.
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.GameAction(Action action)
   at SEModAPIInternal.API.Entity.BaseEntityNetworkManager.BroadcastRemoveEntity(IMyEntity
 entity, Boolean safe)
   at EssentialsPlugin.ProcessHandler.ProcessNewUserTransport.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass2.<PluginProcessing>b__0()
2015-01-01 17:33:54.116 - Greeting Removed => 76561198*******33

<<<<

This has happened for the past 2 or 3 days.
Thanks.

**Comment by McyD** [comment]
Why would you run the GPS mod at the same time as essentials?  The GPS is already in Essentials... try taking the GPS mod out.

**Comment by tbankstemp** [comment]
I have it disabled in Essentials, because it wasn't working right, even before adding the GPS mod in.

**Comment by Tyrsis** [comment]
Sorry I'm catching up to posts.  You need to give me logs and put them on pastebin.com or paste.ee so I can look at the full log.  Partials do not help me find the problem.
