### ISSUE TITLE
Error from micropatch by Keen with SESE

### ISSUE THREAD

**Issue by Dogtrigger** [Tyrsis/SE-Community-Mod-API#24]
Pasted is the error log I'm seeing since the micro patch this morning. I removed only my unique character ID, rest is straight from the log.

2015-01-02 11:23:19.826 - Thread: 4 -> Log Started
2015-01-02 11:23:19.826 - Thread: 4 -> Timezone (local - UTC): -5h
2015-01-02 11:23:19.827 - Thread: 4 -> App Version: 0.2.4.5
2015-01-02 11:23:19.827 - Thread: 4 -> MyAPIGateway Initialized
2015-01-02 11:23:19.845 - Thread: 4 -> Initializing plugin at C:\ProgramData\SpaceEngineersDedicated\Sector 13 Gaming\Mods\BlueprintPlugin\BlueprintsPlugin.dll - 774c4148-1da1-4ee0-b7f0-eb51ca296e9b'
2015-01-02 11:23:19.851 - Thread: 4 -> Blueprints Plugin initialized!
2015-01-02 11:23:19.858 - Thread: 4 -> Loading Settings File: C:\ProgramData\SpaceEngineersDedicated\Sector 13 Gaming\Mods\BlueprintPlugin\Blueprints-Settings.xml
2015-01-02 11:23:19.953 - Thread: 4 -> Initializing plugin at C:\ProgramData\SpaceEngineersDedicated\Sector 13 Gaming\Mods\DockingPlugin\Docking.dll - 35847311-03f6-4e63-a422-253f0c126d8b'
2015-01-02 11:23:19.954 - Thread: 4 -> Init(String): C:\ProgramData\SpaceEngineersDedicated\Sector 13 Gaming\Mods\DockingPlugin\Docking.dll
2015-01-02 11:23:19.998 - Thread: 4 -> Docking Plugin '35847311-03f6-4e63-a422-253f0c126d8b' initialized! (199, 20)
2015-01-02 11:23:20.020 - Thread: 4 -> Initializing plugin at C:\ProgramData\SpaceEngineersDedicated\Sector 13 Gaming\Mods\Essentials\Essentials.dll - f767bda5-0a8c-4813-85fd-a5a2341778e8'
2015-01-02 11:23:20.041 - Thread: 4 -> Stopping all ships
2015-01-02 11:23:20.054 - Thread: 4 -> 0 ships have been stopped
2015-01-02 11:23:20.061 - Thread: 4 -> Plugin 'Dedicated Server Essentials' initialized. (Version: 1.0.2.1197  ID: f767bda5-0a8c-4813-85fd-a5a2341778e8)
2015-01-02 11:23:40.006 - Thread: 12 -> Failed to get entity method 'CE1BE0AFCC72AC4B3DD4097DC99323F6': Method not found
2015-01-02 11:23:40.008 - Thread: 12 -> Failed to invoke entity method 'CE1BE0AFCC72AC4B3DD4097DC99323F6' on type '5BCAC68007431E61367F5B2CF24E2D6F.714451095FE0D12C399607EAC612A6FE': Method is empty
2015-01-02 11:23:40.010 - Thread: 12 -> Failed to get entity method '688E539EA170C9AEED2E656A3C3FD7DF': Method not found
2015-01-02 11:23:40.010 - Thread: 12 -> Failed to invoke entity method '688E539EA170C9AEED2E656A3C3FD7DF' on type '5BCAC68007431E61367F5B2CF24E2D6F.714451095FE0D12C399607EAC612A6FE': Method is empty
2015-01-02 11:24:20.085 - Thread: 27 -> Docking (1.0.1.185) - Ping? Pong! 11:24 AM
2015-01-02 11:25:20.148 - Thread: 27 -> Docking (1.0.1.185) - Ping? Pong! 11:25 AM
2015-01-02 11:26:17.574 - Thread: 4 -> New User: (deleted by me)
2015-01-02 11:26:17.575 - Thread: 4 -> Greeting Added => (deleted by me) (New user: True)
2015-01-02 11:26:20.205 - Thread: 27 -> Docking (1.0.1.185) - Ping? Pong! 11:26 AM
2015-01-02 11:26:50.309 - Thread: 37 -> ProcessCommunication: Problem getting entities, skipping update
2015-01-02 11:27:00.100 - Thread: 12 -> Failed to get entity method 'CE1BE0AFCC72AC4B3DD4097DC99323F6': Method not found
2015-01-02 11:27:00.101 - Thread: 12 -> Failed to invoke entity method 'CE1BE0AFCC72AC4B3DD4097DC99323F6' on type '5BCAC68007431E61367F5B2CF24E2D6F.714451095FE0D12C399607EAC612A6FE': Method is empty
2015-01-02 11:27:00.102 - Thread: 12 -> Failed to get entity method '688E539EA170C9AEED2E656A3C3FD7DF': Method not found
2015-01-02 11:27:00.103 - Thread: 12 -> Failed to invoke entity method '688E539EA170C9AEED2E656A3C3FD7DF' on type '5BCAC68007431E61367F5B2CF24E2D6F.714451095FE0D12C399607EAC612A6FE': Method is empty
2015-01-02 11:27:00.107 - Thread: 12 -> Failed to get entity method 'CE1BE0AFCC72AC4B3DD4097DC99323F6': Method not found
2015-01-02 11:27:00.107 - Thread: 12 -> Failed to invoke entity method 'CE1BE0AFCC72AC4B3DD4097DC99323F6' on type '5BCAC68007431E61367F5B2CF24E2D6F.714451095FE0D12C399607EAC612A6FE': Method is empty
2015-01-02 11:27:00.108 - Thread: 12 -> Failed to get entity method '688E539EA170C9AEED2E656A3C3FD7DF': Method not found
2015-01-02 11:27:00.109 - Thread: 12 -> Failed to invoke entity method '688E539EA170C9AEED2E656A3C3FD7DF' on type '5BCAC68007431E61367F5B2CF24E2D6F.714451095FE0D12C399607EAC612A6FE': Method is empty
2015-01-02 11:27:00.125 - Thread: 12 -> Failed to get entity method 'CE1BE0AFCC72AC4B3DD4097DC99323F6': Method not found
2015-01-02 11:27:00.126 - Thread: 12 -> Failed to invoke entity method 'CE1BE0AFCC72AC4B3DD4097DC99323F6' on type '5BCAC68007431E61367F5B2CF24E2D6F.714451095FE0D12C399607EAC612A6FE': Method is empty
2015-01-02 11:27:00.127 - Thread: 12 -> Failed to get entity method '688E539EA170C9AEED2E656A3C3FD7DF': Method not found
2015-01-02 11:27:00.127 - Thread: 12 -> Failed to invoke entity method '688E539EA170C9AEED2E656A3C3FD7DF' on type '5BCAC68007431E61367F5B2CF24E2D6F.714451095FE0D12C399607EAC612A6FE': Method is empty
2015-01-02 11:27:00.139 - Thread: 12 -> Failed to get entity method 'CE1BE0AFCC72AC4B3DD4097DC99323F6': Method not found
2015-01-02 11:27:00.140 - Thread: 12 -> Failed to invoke entity method 'CE1BE0AFCC72AC4B3DD4097DC99323F6' on type '5BCAC68007431E61367F5B2CF24E2D6F.714451095FE0D12C399607EAC612A6FE': Method is empty
2015-01-02 11:27:00.141 - Thread: 12 -> Failed to get entity method '688E539EA170C9AEED2E656A3C3FD7DF': Method not found
2015-01-02 11:27:00.142 - Thread: 12 -> Failed to invoke entity method '688E539EA170C9AEED2E656A3C3FD7DF' on type '5BCAC68007431E61367F5B2CF24E2D6F.714451095FE0D12C399607EAC612A6FE': Method is empty
2015-01-02 11:27:00.145 - Thread: 12 -> Failed to get entity method 'CE1BE0AFCC72AC4B3DD4097DC99323F6': Method not found
2015-01-02 11:27:00.145 - Thread: 12 -> Failed to invoke entity method 'CE1BE0AFCC72AC4B3DD4097DC99323F6' on type '5BCAC68007431E61367F5B2CF24E2D6F.714451095FE0D12C399607EAC612A6FE': Method is empty
2015-01-02 11:27:00.146 - Thread: 12 -> Failed to get entity method '688E539EA170C9AEED2E656A3C3FD7DF': Method not found
2015-01-02 11:27:00.147 - Thread: 12 -> Failed to invoke entity method '688E539EA170C9AEED2E656A3C3FD7DF' on type '5BCAC68007431E61367F5B2CF24E2D6F.714451095FE0D12C399607EAC612A6FE': Method is empty
2015-01-02 11:27:00.153 - Thread: 12 -> Failed to get entity method 'CE1BE0AFCC72AC4B3DD4097DC99323F6': Method not found
2015-01-02 11:27:00.154 - Thread: 12 -> Failed to invoke entity method 'CE1BE0AFCC72AC4B3DD4097DC99323F6' on type '5BCAC68007431E61367F5B2CF24E2D6F.714451095FE0D12C399607EAC612A6FE': Method is empty
2015-01-02 11:27:00.155 - Thread: 12 -> Failed to get entity method '688E539EA170C9AEED2E656A3C3FD7DF': Method not found
2015-01-02 11:27:00.155 - Thread: 12 -> Failed to invoke entity method '688E539EA170C9AEED2E656A3C3FD7DF' on type '5BCAC68007431E61367F5B2CF24E2D6F.714451095FE0D12C399607EAC612A6FE': Method is empty
2015-01-02 11:27:00.627 - Thread: 4 -> Greeting Removed => (deleted by me)
2015-01-02 11:27:01.433 - Thread: 12 -> TargetInvocationException - Server crashed
2015-01-02 11:27:01.434 - Thread: 12 -> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'Sandbox.ModAPI.IMyInventory' from assembly 'Sandbox.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SEModAPIInternal.API.Entity.InventoryEntity.<>c__DisplayClass5.<get_Items>b__4()
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.<>c__DisplayClassa.<GameAction>b__7()
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.03AD891A5752B7EFAD2BBE2F577984D6()
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.61609B53E1E854349A6BB142FE7EA0CC()
   at 168638249D29224100DB50BB468E7C07.7BAD4AFD06B91BCD63EA57F7C0D4F408.2457E95BE2F0D1F1A4A009B2B1DBBDA4()
   at 168638249D29224100DB50BB468E7C07.398AD1E315E6E4D570C424BD0D168FC1.858DA51EB20785A82D9A03614304088A.0187A29A24275EC024A192E7E235CC2E.9C41E76459B99591F991CBA0833BD17E()
   at 168638249D29224100DB50BB468E7C07.6E0E814918D8AD6B2DC9CA5005102256.90812081676EB4C493FF905C91F8B259(9AA159E6C22F64A542015EED199D04B9 148A5BA193EB90E55F5E805EF96CAD48)
   at 168638249D29224100DB50BB468E7C07.398AD1E315E6E4D570C424BD0D168FC1.90812081676EB4C493FF905C91F8B259(9AA159E6C22F64A542015EED199D04B9 148A5BA193EB90E55F5E805EF96CAD48)
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.246E732EE67F7F6F88C4FF63B3901107(Boolean FF8E4184144DE7049FF5EC07D594DAB6, Action 8CF1B812E214DD1C51DD894D4C05D44A)
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.523C8831DA5DAB3A19F6D33A2C6437B5()
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.26A7ABEA729FAE1F24679E21470F8E98(String 8BF03A34188889479CB413E58490FC37, String 48C45E39212AAA2B19C972DA9195F48A, Boolean 7AC487C1B445CD9F481CF5FE695A7CEA, Boolean 4292A7A4DACAF323E558B7E11DD3CF00)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at SEModAPIInternal.API.Server.ServerAssemblyWrapper.StartServer(String instanceName, String overridePath, Boolean useConsole)
2015-01-02 11:27:01.435 - Thread: 12 -> System.TypeLoadException: Could not load type 'Sandbox.ModAPI.IMyInventory' from assembly 'Sandbox.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SEModAPIInternal.API.Entity.InventoryEntity.<>c__DisplayClass5.<get_Items>b__4()
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.<>c__DisplayClassa.<GameAction>b__7()
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.03AD891A5752B7EFAD2BBE2F577984D6()
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.61609B53E1E854349A6BB142FE7EA0CC()
   at 168638249D29224100DB50BB468E7C07.7BAD4AFD06B91BCD63EA57F7C0D4F408.2457E95BE2F0D1F1A4A009B2B1DBBDA4()
   at 168638249D29224100DB50BB468E7C07.398AD1E315E6E4D570C424BD0D168FC1.858DA51EB20785A82D9A03614304088A.0187A29A24275EC024A192E7E235CC2E.9C41E76459B99591F991CBA0833BD17E()
   at 168638249D29224100DB50BB468E7C07.6E0E814918D8AD6B2DC9CA5005102256.90812081676EB4C493FF905C91F8B259(9AA159E6C22F64A542015EED199D04B9 148A5BA193EB90E55F5E805EF96CAD48)
   at 168638249D29224100DB50BB468E7C07.398AD1E315E6E4D570C424BD0D168FC1.90812081676EB4C493FF905C91F8B259(9AA159E6C22F64A542015EED199D04B9 148A5BA193EB90E55F5E805EF96CAD48)
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.246E732EE67F7F6F88C4FF63B3901107(Boolean FF8E4184144DE7049FF5EC07D594DAB6, Action 8CF1B812E214DD1C51DD894D4C05D44A)
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.523C8831DA5DAB3A19F6D33A2C6437B5()
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.26A7ABEA729FAE1F24679E21470F8E98(String 8BF03A34188889479CB413E58490FC37, String 48C45E39212AAA2B19C972DA9195F48A, Boolean 7AC487C1B445CD9F481CF5FE695A7CEA, Boolean 4292A7A4DACAF323E558B7E11DD3CF00)
2015-01-02 11:27:01.435 - Thread: 12 ->    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at SEModAPIInternal.API.Server.ServerAssemblyWrapper.StartServer(String instanceName, String overridePath, Boolean useConsole)
   at SEModAPIExtensions.API.Server.RunServer()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2015-01-02 11:27:01.440 - Thread: 12 -> Unloading plugin 'f767bda5-0a8c-4813-85fd-a5a2341778e8'
2015-01-02 11:27:01.441 - Thread: 12 -> Shutting down plugin: Dedicated Server Essentials - 1.0.2.1197
2015-01-02 11:27:01.567 - Thread: 12 -> Unloading plugin '35847311-03f6-4e63-a422-253f0c126d8b'
2015-01-02 11:27:01.569 - Thread: 27 -> Docking plugin: Shutting down processing thread: System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at Docking.PluginDocking.processDocking()
2015-01-02 11:27:01.578 - Thread: 12 -> Unloading plugin '774c4148-1da1-4ee0-b7f0-eb51ca296e9b'
2015-01-02 11:27:01.588 - Thread: 12 -> Shutting down Blueprints Plugin
2015-01-02 11:27:01.764 - Thread: 26 -> LicenseCost: 0:0  LicenseCostPerBlock: 0:9
2015-01-02 11:27:01.946 - Thread: 26 -> Blueprints Processing Thread Closed: System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at BlueprintsPlugin.BlueprintsPlugin.BlueprintsThreadWork()

**Comment by Tyrsis** [comment]
Yeah releasing patch soon to extender.
