### ISSUE TITLE
Crash on Scrap Command

### ISSUE THREAD

**Issue by LordNex** [Tyrsis/SE-Community-Mod-API#25]
2015-01-02 15:45:36.357 - Thread: 14 -> Log Started
2015-01-02 15:45:36.358 - Thread: 14 -> Timezone (local - UTC): -6h
2015-01-02 15:45:36.358 - Thread: 14 -> App Version: 0.2.4.5
2015-01-02 15:45:36.358 - Thread: 14 -> MyAPIGateway Initialized
2015-01-02 15:45:36.373 - Thread: 14 -> Initializing plugin at C:\ProgramData\SpaceEngineersDedicated\POWSE\Mods\BlueprintPlugin\BlueprintsPlugin.dll - 774c4148-1da1-4ee0-b7f0-eb51ca296e9b'
2015-01-02 15:45:36.379 - Thread: 14 -> Blueprints Plugin initialized!
2015-01-02 15:45:36.386 - Thread: 14 -> Loading Settings File: C:\ProgramData\SpaceEngineersDedicated\POWSE\Mods\BlueprintPlugin\Blueprints-Settings.xml
2015-01-02 15:45:36.581 - Thread: 14 -> Can not find CubeBlocks definition in: C:\ProgramData\SpaceEngineersDedicated\POWSE\Mods\315645140.sbm
2015-01-02 15:45:36.582 - Thread: 14 -> Can not find CubeBlocks definition in: C:\ProgramData\SpaceEngineersDedicated\POWSE\Mods\321588701.sbm
2015-01-02 15:45:36.601 - Thread: 14 -> Can not find CubeBlocks definition in: C:\ProgramData\SpaceEngineersDedicated\POWSE\Mods\328494103.sbm
2015-01-02 15:45:36.603 - Thread: 14 -> Can not find CubeBlocks definition in: C:\ProgramData\SpaceEngineersDedicated\POWSE\Mods\331118634.sbm
2015-01-02 15:45:36.616 - Thread: 14 -> Can not find CubeBlocks definition in: C:\ProgramData\SpaceEngineersDedicated\POWSE\Mods\347400064.sbm
2015-01-02 15:45:36.621 - Thread: 14 -> Initializing plugin at C:\ProgramData\SpaceEngineersDedicated\POWSE\Mods\Essentials\Essentials.dll - f767bda5-0a8c-4813-85fd-a5a2341778e8'
2015-01-02 15:45:37.014 - Thread: 14 -> Stopping all ships
2015-01-02 15:45:37.189 - Thread: 14 -> 1 ships have been stopped
2015-01-02 15:45:37.215 - Thread: 28 -> Checking 0 log files for logins
2015-01-02 15:45:37.219 - Thread: 14 -> Plugin 'Dedicated Server Essentials' initialized. (Version: 1.0.2.1197  ID: f767bda5-0a8c-4813-85fd-a5a2341778e8)
2015-01-02 15:45:37.229 - Thread: 28 -> Completed checking logs in 0.0130007s: 136 (0) steamIds
2015-01-02 15:54:30.935 - Thread: 12 -> Asynchronous Save Setup Started: 229.013ms
2015-01-02 15:54:34.992 - Thread: 7 -> Asynchronous Save Completed: 4286.2451ms
2015-01-02 16:04:30.908 - Thread: 12 -> Asynchronous Save Setup Started: 192.011ms
2015-01-02 16:04:34.804 - Thread: 46 -> Asynchronous Save Completed: 4087.2338ms
2015-01-02 16:14:30.892 - Thread: 12 -> Asynchronous Save Setup Started: 165.0094ms
2015-01-02 16:14:34.771 - Thread: 28 -> Asynchronous Save Completed: 4044.2313ms
2015-01-02 16:24:30.923 - Thread: 12 -> Asynchronous Save Setup Started: 184.0106ms
2015-01-02 16:24:34.901 - Thread: 9 -> Asynchronous Save Completed: 4162.2381ms
2015-01-02 16:34:30.928 - Thread: 12 -> Asynchronous Save Setup Started: 176.0101ms
2015-01-02 16:34:34.813 - Thread: 7 -> Asynchronous Save Completed: 4061.2323ms
2015-01-02 16:44:30.937 - Thread: 12 -> Asynchronous Save Setup Started: 177.0101ms
2015-01-02 16:44:34.824 - Thread: 30 -> Asynchronous Save Completed: 4064.2325ms
2015-01-02 16:54:30.932 - Thread: 12 -> Asynchronous Save Setup Started: 161.0092ms
2015-01-02 16:54:34.829 - Thread: 17 -> Asynchronous Save Completed: 4058.2321ms
2015-01-02 17:04:30.958 - Thread: 12 -> Asynchronous Save Setup Started: 172.0098ms
2015-01-02 17:04:34.853 - Thread: 46 -> Asynchronous Save Completed: 4067.2326ms
2015-01-02 17:14:30.980 - Thread: 12 -> Asynchronous Save Setup Started: 182.0104ms
2015-01-02 17:14:34.821 - Thread: 17 -> Asynchronous Save Completed: 4023.2301ms
2015-01-02 17:24:30.974 - Thread: 12 -> Asynchronous Save Setup Started: 168.0096ms
2015-01-02 17:24:34.937 - Thread: 14 -> Asynchronous Save Completed: 4132.2364ms
2015-01-02 17:34:31.013 - Thread: 12 -> Asynchronous Save Setup Started: 198.0113ms
2015-01-02 17:34:34.917 - Thread: 47 -> Asynchronous Save Completed: 4102.2346ms
2015-01-02 17:44:31.002 - Thread: 12 -> Asynchronous Save Setup Started: 176.01ms
2015-01-02 17:44:34.949 - Thread: 28 -> Asynchronous Save Completed: 4122.2357ms
2015-01-02 17:54:30.997 - Thread: 12 -> Asynchronous Save Setup Started: 158.009ms
2015-01-02 17:54:34.911 - Thread: 45 -> Asynchronous Save Completed: 4072.2329ms
2015-01-02 18:04:31.023 - Thread: 12 -> Asynchronous Save Setup Started: 171.0098ms
2015-01-02 18:04:34.892 - Thread: 9 -> Asynchronous Save Completed: 4040.2311ms
2015-01-02 18:14:31.043 - Thread: 12 -> Asynchronous Save Setup Started: 182.0104ms
2015-01-02 18:14:34.878 - Thread: 47 -> Asynchronous Save Completed: 4017.2298ms
2015-01-02 18:24:31.048 - Thread: 12 -> Asynchronous Save Setup Started: 176.0101ms
2015-01-02 18:24:34.886 - Thread: 46 -> Asynchronous Save Completed: 4014.2296ms
2015-01-02 18:34:31.029 - Thread: 12 -> Asynchronous Save Setup Started: 148.0084ms
2015-01-02 18:34:34.929 - Thread: 28 -> Asynchronous Save Completed: 4048.2315ms
2015-01-02 18:44:31.068 - Thread: 12 -> Asynchronous Save Setup Started: 174.0099ms
2015-01-02 18:44:34.944 - Thread: 30 -> Asynchronous Save Completed: 4049.2316ms
2015-01-02 18:45:37.173 - Thread: 45 -> New User Transport Queued: 76561197965737490
2015-01-02 18:45:37.176 - Thread: 45 -> New User: 76561197965737490
2015-01-02 18:45:37.176 - Thread: 45 -> Greeting Added => 76561197965737490 (New user: False)
2015-01-02 18:53:09.355 - Thread: 32 -> Player entered game, starting movement.
2015-01-02 18:53:09.868 - Thread: 42 -> Player in game, creating waypoints
2015-01-02 18:54:31.097 - Thread: 12 -> Asynchronous Save Setup Started: 193.0111ms
2015-01-02 18:54:35.044 - Thread: 44 -> Asynchronous Save Completed: 4140.2368ms
2015-01-02 18:54:48.003 - Thread: 12 -> Disposing CharacterEntity 'StuffYouFear'
2015-01-02 19:04:31.108 - Thread: 12 -> Asynchronous Save Setup Started: 193.0111ms
2015-01-02 19:04:35.012 - Thread: 7 -> Asynchronous Save Completed: 4097.2344ms
2015-01-02 19:14:31.085 - Thread: 12 -> Asynchronous Save Setup Started: 158.009ms
2015-01-02 19:14:34.982 - Thread: 46 -> Asynchronous Save Completed: 4054.2318ms
2015-01-02 19:24:31.117 - Thread: 12 -> Asynchronous Save Setup Started: 180.0103ms
2015-01-02 19:24:35.069 - Thread: 17 -> Asynchronous Save Completed: 4132.2364ms
2015-01-02 19:34:31.113 - Thread: 12 -> Asynchronous Save Setup Started: 162.0092ms
2015-01-02 19:34:35.037 - Thread: 9 -> Asynchronous Save Completed: 4086.2337ms
2015-01-02 19:44:31.167 - Thread: 12 -> Asynchronous Save Setup Started: 208.0119ms
2015-01-02 19:44:35.132 - Thread: 45 -> Asynchronous Save Completed: 4172.2386ms
2015-01-02 19:54:31.162 - Thread: 12 -> Asynchronous Save Setup Started: 192.011ms
2015-01-02 19:54:35.101 - Thread: 44 -> Asynchronous Save Completed: 4131.2363ms
2015-01-02 20:04:31.202 - Thread: 12 -> Asynchronous Save Setup Started: 220.0125ms
2015-01-02 20:04:35.093 - Thread: 17 -> Asynchronous Save Completed: 4111.2351ms
2015-01-02 20:14:31.158 - Thread: 12 -> Asynchronous Save Setup Started: 166.0095ms
2015-01-02 20:14:35.026 - Thread: 17 -> Asynchronous Save Completed: 4034.2307ms
2015-01-02 20:15:08.966 - Thread: 14 -> New User Transport Queued: 76561198122241078
2015-01-02 20:15:08.968 - Thread: 14 -> New User: 76561198122241078
2015-01-02 20:15:08.968 - Thread: 14 -> Greeting Added => 76561198122241078 (New user: False)
2015-01-02 20:18:59.480 - Thread: 32 -> Player entered game, starting movement.
2015-01-02 20:19:01.432 - Thread: 42 -> Player in game, creating waypoints
2015-01-02 20:24:31.186 - Thread: 12 -> Asynchronous Save Setup Started: 183.0105ms
2015-01-02 20:24:35.060 - Thread: 46 -> Asynchronous Save Completed: 4057.2321ms
2015-01-02 20:28:11.382 - Thread: 46 -> Command_Sy()
2015-01-02 20:28:11.722 - Thread: 46 -> Prefered name: CRUCIBLE
2015-01-02 20:28:12.071 - Thread: 12 -> TargetInvocationException - Server crashed
2015-01-02 20:28:12.071 - Thread: 12 -> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'Sandbox.ModAPI.IMyInventory' from assembly 'Sandbox.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at BlueprintsPlugin.Utility.Entity.<>c__DisplayClass1a.<CheckMaterials>b__17()
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.<>c__DisplayClassa.<GameAction>b__7()
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.03AD891A5752B7EFAD2BBE2F577984D6()
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.61609B53E1E854349A6BB142FE7EA0CC()
   at 168638249D29224100DB50BB468E7C07.7BAD4AFD06B91BCD63EA57F7C0D4F408.2457E95BE2F0D1F1A4A009B2B1DBBDA4()
   at 168638249D29224100DB50BB468E7C07.398AD1E315E6E4D570C424BD0D168FC1.858DA51EB20785A82D9A03614304088A.0187A29A24275EC024A192E7E235CC2E.9C41E76459B99591F991CBA0833BD17E()
   at 168638249D29224100DB50BB468E7C07.6E0E814918D8AD6B2DC9CA5005102256.90812081676EB4C493FF905C91F8B259(9AA159E6C22F64A542015EED199D04B9 148A5BA193EB90E55F5E805EF96CAD48)
   at 168638249D29224100DB50BB468E7C07.398AD1E315E6E4D570C424BD0D168FC1.90812081676EB4C493FF905C91F8B259(9AA159E6C22F64A542015EED199D04B9 148A5BA193EB90E55F5E805EF96CAD48)
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.246E732EE67F7F6F88C4FF63B3901107(Boolean FF8E4184144DE7049FF5EC07D594DAB6, Action 8CF1B812E214DD1C51DD894D4C05D44A)
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.523C8831DA5DAB3A19F6D33A2C6437B5()
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.26A7ABEA729FAE1F24679E21470F8E98(String 8BF03A34188889479CB413E58490FC37, String 48C45E39212AAA2B19C972DA9195F48A, Boolean 7AC487C1B445CD9F481CF5FE695A7CEA, Boolean 4292A7A4DACAF323E558B7E11DD3CF00)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at SEModAPIInternal.API.Server.ServerAssemblyWrapper.StartServer(String instanceName, String overridePath, Boolean useConsole)
2015-01-02 20:28:12.071 - Thread: 12 -> System.TypeLoadException: Could not load type 'Sandbox.ModAPI.IMyInventory' from assembly 'Sandbox.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at BlueprintsPlugin.Utility.Entity.<>c__DisplayClass1a.<CheckMaterials>b__17()
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.<>c__DisplayClassa.<GameAction>b__7()
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.03AD891A5752B7EFAD2BBE2F577984D6()
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.61609B53E1E854349A6BB142FE7EA0CC()
   at 168638249D29224100DB50BB468E7C07.7BAD4AFD06B91BCD63EA57F7C0D4F408.2457E95BE2F0D1F1A4A009B2B1DBBDA4()
   at 168638249D29224100DB50BB468E7C07.398AD1E315E6E4D570C424BD0D168FC1.858DA51EB20785A82D9A03614304088A.0187A29A24275EC024A192E7E235CC2E.9C41E76459B99591F991CBA0833BD17E()
   at 168638249D29224100DB50BB468E7C07.6E0E814918D8AD6B2DC9CA5005102256.90812081676EB4C493FF905C91F8B259(9AA159E6C22F64A542015EED199D04B9 148A5BA193EB90E55F5E805EF96CAD48)
   at 168638249D29224100DB50BB468E7C07.398AD1E315E6E4D570C424BD0D168FC1.90812081676EB4C493FF905C91F8B259(9AA159E6C22F64A542015EED199D04B9 148A5BA193EB90E55F5E805EF96CAD48)
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.246E732EE67F7F6F88C4FF63B3901107(Boolean FF8E4184144DE7049FF5EC07D594DAB6, Action 8CF1B812E214DD1C51DD894D4C05D44A)
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.523C8831DA5DAB3A19F6D33A2C6437B5()
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.26A7ABEA729FAE1F24679E21470F8E98(String 8BF03A34188889479CB413E58490FC37, String 48C45E39212AAA2B19C972DA9195F48A, Boolean 7AC487C1B445CD9F481CF5FE695A7CEA, Boolean 4292A7A4DACAF323E558B7E11DD3CF00)
2015-01-02 20:28:12.071 - Thread: 12 ->    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at SEModAPIInternal.API.Server.ServerAssemblyWrapper.StartServer(String instanceName, String overridePath, Boolean useConsole)
   at SEModAPIExtensions.API.Server.RunServer()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2015-01-02 20:28:12.086 - Thread: 12 -> Unloading plugin 'f767bda5-0a8c-4813-85fd-a5a2341778e8'
2015-01-02 20:28:12.086 - Thread: 12 -> Shutting down plugin: Dedicated Server Essentials - 1.0.2.1197
2015-01-02 20:28:12.274 - Thread: 12 -> Unloading plugin '774c4148-1da1-4ee0-b7f0-eb51ca296e9b'
2015-01-02 20:28:12.289 - Thread: 12 -> Shutting down Blueprints Plugin
2015-01-02 20:28:12.305 - Thread: 29 -> LicenseCost: 0:9  LicenseCostPerBlock: 9:9
2015-01-02 20:28:12.336 - Thread: 29 -> Blueprints Processing Thread Closed: System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at BlueprintsPlugin.BlueprintsPlugin.BlueprintsThreadWork()

**Comment by Tyrsis** [comment]
Requires testing.  I am moving shipyards into essentials so I will fix then when that happens.  Should be soon(tm)
