### ISSUE TITLE
waypoint error issue

### ISSUE THREAD

**Issue by EngineerBean** [Tyrsis/SE-Community-Mod-API#27]
can you assist with what is causing this problem with loading player waypoints please.

2015-01-09 07:44:05.805 - Thread: 11 -> Log Started
2015-01-09 07:44:05.805 - Thread: 11 -> Timezone (local - UTC): 11h
2015-01-09 07:44:05.806 - Thread: 11 -> App Version: 0.2.4.5
2015-01-09 07:44:05.806 - Thread: 11 -> MyAPIGateway Initialized
2015-01-09 07:44:05.827 - Thread: 11 -> Initializing plugin at C:\ProgramData\SpaceEngineersDedicated\Daily-Backups\Mods\Essentials\Essentials.dll - f767bda5-0a8c-4813-85fd-a5a2341778e8'
2015-01-09 07:44:06.414 - Thread: 11 -> Stopping all ships
2015-01-09 07:44:08.733 - Thread: 11 -> 1 ships have been stopped
2015-01-09 07:44:08.747 - Thread: 11 -> Plugin 'Dedicated Server Essentials' initialized. (Version: 1.0.2.1208  ID: f767bda5-0a8c-4813-85fd-a5a2341778e8)
2015-01-09 07:45:15.070 - Thread: 31 -> New User: 76561198096039031
2015-01-09 07:45:15.070 - Thread: 31 -> Greeting Added => 76561198096039031 (New user: False)
2015-01-09 07:49:17.602 - Thread: 29 -> Player in game, creating waypoints
2015-01-09 07:49:17.654 - Thread: 29 -> Waypoint Load Error: System.InvalidOperationException: There is an error in XML document (4652, 18). ---> System.Xml.XmlException: Unexpected end of file has occurred. The following elements are not closed: WaypointItem, WaypointItems, Waypoints. Line 4652, position 18.
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlReader.ReadEndElement()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderWaypoints.Read2_Vector3D(Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderWaypoints.Read4_WaypointItem(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderWaypoints.Read5_Waypoints(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderWaypoints.Read6_Waypoints()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at EssentialsPlugin.Utility.Waypoints.Load()
2015-01-09 07:49:17.655 - Thread: 29 -> Handler Problems: 5000 - System.NullReferenceException: Object reference not set to an instance of an object.
   at EssentialsPlugin.ProcessHandler.ProcessWaypoints.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass2.<PluginProcessing>b__0()
2015-01-09 07:51:36.525 - Thread: 8 -> Asynchronous Save Setup Started: 319.0183ms

**Comment by Tyrsis** [comment]
It looks like your XML was corrupted, maybe a crash during the save?

**Comment by EngineerBean** [comment]
thanks for the help, i found the problem in the waypoints.xml, wasn't closed off with 2 lines at end..
  </WaypointItems>
</Waypoints>
