### ISSUE TITLE
Server crash with increasing frequency.

### ISSUE THREAD

**Issue by qwert75** [Tyrsis/SE-Community-Mod-API#42]
hi,

currently have a dedicated server with hostaspace.

uptodate SESE and 
uptodate dedicated server essentials.

entries from log file, whole log file can be found here:
https://www.dropbox.com/s/0kahwtrcdlhs7ib/SEModAPIInternal_2015_1_29_0_57_16.log?dl=0

can take several hours, can happen about 10 minutes after a reboot, cannot identify any cause.

**Comment by dodexahedron** [comment]
That's happening in a block-related method in the game itself.
It doesn't appear to be internal to Extender.  Chances are it is related to a mod.
Run your server without extender and see if you encounter the same issues.

**Comment by qwert75** [comment]
Finally been able to cause a crash myself, seems to be when a player logs in and sends a message. ive removed all mods on my test server and attempted it and can cause the same crash

**Comment by qwert75** [comment]
Turning off extender fixes issue completely

**Comment by dodexahedron** [comment]
Will have a look at the chat methods later.  Can you share your world? I'm able to chat, on my server, both as a user and from extender on the chat tab.

**Comment by qwert75** [comment]
i just made an empty world loaded it up with only extender running, no essentials plugin, no mods

type:

"testing if this will crash"

message appears in chat then "server host left the game"

https://www.dropbox.com/s/hej1kve8sxl2tvf/SEModAPIInternal.log.zip?dl=0

that's the new log file after update,

0 point in giving you world file as it is doing it on a new empty world

**Comment by Tyrsis** [comment]
This is due to patch, issues are unrelated.

**Comment by dodexahedron** [comment]
Are you sure? He did report it before the patch came out, and his stack trace had obfuscated method names that matched the pre-patch version of SE.  If you've got the time now, you want to look at it?  Otherwise I can have a look later tonight.

**Comment by qwert75** [comment]
latest SE extender patch fixed, thanks guys

**Comment by Tyrsis** [comment]
The first crash he reported was "something".  Not sure if it's extender related.  The second crash was due to patch.  That is what I meant by unrelated, and why I kept it open.

**Comment by qwert75** [comment]
ive got a parallel server running with exact same world, only difference is its not running essentials, i believe the issue may be there instead, as that server isn't crashing at all, should i move issue over to there?

**Comment by Tyrsis** [comment]
Yes though toggling dynamic conceal and forcing reveal can be very dangerous, and may be the cause of your issues.  Can you get a crash where you don't ever force a reveal?

**Comment by qwert75** [comment]
server never crashes when i force one, it just seems to be random, i mean i had one where i committed suicide, that could be a conceal thing where its revealing my med bays, but im no expert.

now i think about it its set to conceal med bays, might be worth while setting it so that it doesn't conceal with med bays.

**Comment by McyD** [comment]
2015-01-29 17:46:12.311 - Thread: 1 -> Log Started
2015-01-29 17:46:12.311 - Thread: 1 -> Timezone (local - UTC): -5h
2015-01-29 17:46:12.311 - Thread: 1 -> App Version: 0.3.0.1
2015-01-29 17:46:12.312 - Thread: 1 -> Failed to find method '582447224E2B03FA4EAB3D6C2DDD48D9' in type '5F381EA9388E0A32A8C817841E192BE8.0F8EE1AD651CB822CB9635B463AE6CD5'
2015-01-29 17:54:10.690 - Thread: 11 -> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingFieldException: Field not found: 'ChatEvent.message'.
   at EssentialsPlugin.Essentials.OnChatReceived(ChatEvent obj)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at SEModAPIExtensions.API.PluginManager.DoUpdate(Object args)
2015-01-29 17:54:10.690 - Thread: 11 -> System.MissingFieldException: Field not found: 'ChatEvent.message'.
   at EssentialsPlugin.Essentials.OnChatReceived(ChatEvent obj)


Noticed this on last startup with latest version of SE after todays update, not sure if it is related or not.
