### ISSUE TITLE
Restarts are broken in last update

### ISSUE THREAD

**Issue by McyD** [Tyrsis/SE-Community-Mod-API#43]
2015-01-29 17:59:52.880 - Thread: 26 -> Handler Problems: 10000 - System.MissingMethodException: Method not found: 'SEModAPIExtensions.API.CommandLineArgs SEModAPIExtensions.API.Server.get_CommandLineArgs()'.
   at EssentialsPlugin.ProcessHandler.ProcessRestart.DoRestart()
   at EssentialsPlugin.ProcessHandler.ProcessRestart.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass2.<PluginProcessing>b__0()

**Comment by dodexahedron** [comment]
The released version of essentials is not compatible with the released version of SESE. I'll release one that is on my fork.

-----Original Message-----
