### ISSUE TITLE
Server Extender 0.3.0.15-Alpha and SE 01.075

### ISSUE THREAD

**Issue by Devlah** [Tyrsis/SE-Community-Mod-API#64]
Upon starting and loading existing world, the "Entities" tab has no contents (Sector Objects 0).

I'm getting this error at the end of the log:

Finished initializing plugins
2015-03-26 16:39:52.993 - Current Voxel Count: 177
2015-03-26 16:39:53.228 - Handler Problems: 400 - System.TypeLoadException: Could not load type 'VRage.Utils.MyStringId'
 from assembly 'VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SEModAPIInternal.API.Entity.BaseObject..ctor(MyObjectBuilder_Base baseEntity)
   at SEModAPIInternal.API.Entity.BaseEntity..ctor(MyObjectBuilder_EntityBase baseEntity)
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGridEntity..ctor(FileInfo prefabFile)
   at EssentialsPlugin.ProcessHandler.ProcessCommunication.AddGlobalRelay()
   at EssentialsPlugin.ProcessHandler.ProcessCommunication.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass2.<PluginProcessing>b__0()

**Comment by dodexahedron** [comment]
This is because you are not using a current version of SESE.
Please download SESE from here: https://github.com/SEServerExtender/SEServerExtender/releases

**Comment by dodexahedron** [comment]
Also, this repository is long since abandoned.
Please see this url for all future and current development:
https://github.com/SEServerExtender/SEServerExtender

**Comment by LordNex** [comment]
So Tyrsis has quit the project?

**Comment by dodexahedron** [comment]
Whoops.
I misread this as being the SEModCommity original repo.

Yes, he's stepped back and I am carrying the torch, though.
http://forums.keenswh.com/post/show_single_post?pid=1286532713&postcount=4

I wouldn't say he's quit, but he never intended to have to carry the project by himself and no longer has the available time to maintain and expand SESE.

That being said, there are a couple of known issues with the new fork of essentials, so before you switch be sure to disable any automated cleanups you have.  I will have those problems fixed very soon, though (they're the top item on my list to take care of, right now).
